export const Languages = {
    en: {
        home: "Home",
        test: "Test",
        newWord: "New Word",
        about: "About",
        appDesc: `The [SHINE-UG] app is designed to help you memorize foreign language vocabulary. By entering the foreign words you are learning along with their meanings into the system, you can build your own personal vocabulary database. This allows you to expand your vocabulary by using features such as a daily new word, a complete word dictionary, and various quizzes and tests based on the words you have saved.`,
        securityDesc: `For cybersecurity and privacy reasons, the system does not store your confidential personal information (such as passwords), and you can log in using Google or Facebook Login`,
        chooseLanguage: "Choose language!",
        googleLogin: "Google Login",
        facebookLogin: "Facebook Login",
        termOfService: "Terms of Service",
        privacyPolicy: "Privacy Policy",
    },
    mn: {
        home: "Эхлэл",
        test: "Тест",
        newWord: "Шинэ Үг",
        about: "Тухай",
        appDesc: `[SHINE-UG] апп нь гадаад хэлний үг цээжилэхэд зориуглагдсан ба та сурч буй гадаад хэлний үг болон утгыг системд оруулсанаар өөрийн гэсэн үгсийн сантай болох боломжтой юм. Ингэснээр та өөрийн бүртгэсэн шинэ үгсийн хүрээнд, өдөр бүрийн шинэ үг, бүх үгний толь, төрөл бүрийн тест шалгалт зэрэг функцуудыг ашиглан үгсийн сангаа нэмэгдүүлэх боломжтой юм.`,
        securityDesc: `Цахим аюулгүй байдлын үүднээс системд таны хувийн нууц мэдээллийг (нууц дугаар) хадгалахгүй ба Google болон Facebook Login ашиглан нэвтрэх боломжтой.`,
        chooseLanguage: "Хэлээ сонго!",
        googleLogin: "Google хаягаар нэвтрэх",
        facebookLogin: "Facebook хаягаар нэвтрэх",
        termOfService: "Үйлчилгээний Нөхцөл",
        privacyPolicy: "Нууцлалын Бодлого",        
    },
};